CEA-COSMIC/ModOpt

modopt/math/matrix.py
modopt/signal/cost.py
modopt/signal/proximity.py
modopt/tests/test_math.py

- cost function now standardised for all optimisation problems.
- all operators that contribute to the cost (*e.g.* proximity operators and gradient) must contain `cost` method.

update cost function implementation

---

modopt/math/matrix.py
modopt/signal/optimisation.py

- Passed dual variable in condat-vu algorithm to cost function.
- Fixed bug in matrix.py docstrings.

Update cost function parameters

---

modopt/base/__init__.py
modopt/base/np_adjust.py
modopt/base/transform.py
modopt/base/types.py
modopt/tests/test_base.py
modopt/tests/test_image.py
modopt/tests/test_math.py

- Removed unnecessary methods from base.py
- Added unit tests and examples for all remaining methods

Cleanup base

---

.coveragerc
modopt/__init__.py
modopt/base/__init__.py
modopt/base/types.py
modopt/base/wrappers.py
modopt/opt/algorithms.py
modopt/opt/cost.py
modopt/opt/gradient.py
modopt/opt/linear.py
modopt/opt/proximity.py
modopt/signal/wavelet.py
modopt/tests/test_opt.py

* Reformatted optimisation algorithms
* Added exceptions
* Added unit tests

Cleanup opt

---

README.rst
docs/source/index.rst
modopt/info.py
setup.py

- Fixed astropy version to v2.0.4 as >v3.0.0 only supports Python3.

updated install requirements

---

.travis.yml

- Downgraded Sphinx to v1.5.6 to fix CI issues.

downgraded sphinx version

---

.travis.yml
docs/source/index.rst
modopt/base/observable.py
modopt/info.py
modopt/math/metrics.py

Cleaned-up metrics module.
- Modified docstrings
- Fixed PEP8 styling
- Removed debugging print statement
- Set default mask to None for SSIM method

Clean metrics

---

README.rst
docs/source/index.rst
modopt/info.py
modopt/interface/log.py
requirements.txt
setup.py

- Changed log name to log file name
- Closing message includes log file name

updated log handling

---

.travis.yml
README.rst
docs/source/index.rst
modopt/base/observable.py
modopt/base/wrappers.py
modopt/info.py
modopt/math/convolve.py
modopt/math/matrix.py
modopt/math/metrics.py
modopt/math/stats.py
modopt/opt/algorithms.py
modopt/opt/linear.py
modopt/plot/cost_plot.py
modopt/signal/svd.py
modopt/signal/wavelet.py
modopt/tests/test_math.py
modopt/tests/test_opt.py
modopt/tests/test_signal.py
setup.py

- Removed astropy requirement, package is now optional and be installed by the user
- Convolution operations now default to scipy
- Added optional scikit-image features
- Updated unit tests and increased coverage
- Added option to skip unit tests that require astropy or scikit-image if the packages are not installed

Astropy fix

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Added contribution guidelines
- Added code of conduct

added contributing guidelines

---

modopt/opt/algorithms.py

Corrected inner product in restarting FISTA

---

README.rst
docs/source/index.rst
modopt/info.py
modopt/opt/algorithms.py
modopt/signal/wavelet.py

Resolves several minor issues

---

README.rst
docs/source/index.rst
modopt/info.py
modopt/signal/wavelet.py
setup.py

- Added generic `execute` method for command line interaction.
- `call_mr_transform` now catches stdout from mr_transform that contains the words "bad" or "Error".
- Switched from warning to exception when errors are caught.

improved call_mr_transform error handling

---

README.rst
docs/source/index.rst
modopt/info.py
modopt/opt/algorithms.py

- Fixed bug when kwarg `progress` passed to `ForwardBackward`.
- Enforced verbose in `SetUp`

Progress bug

---

modopt/signal/wavelet.py

corrected trimming for filters in case of non square filters

---

modopt/opt/__init__.py
modopt/opt/proximity.py
modopt/tests/test_opt.py

This PR implements the Elastic Net and the Ridge proximity operator used as regularization when the data is highly correlated

Ridge elastic net

---

.travis.yml
modopt/opt/proximity.py
modopt/tests/test_opt.py

Fix Unsort and raise error

---

modopt/opt/__init__.py
modopt/opt/proximity.py
modopt/tests/test_opt.py
setup.py

This PR handles the proximity operator for group LASSO

Group lasso Proximity

---

modopt/opt/algorithms.py

This resolves #85 
It is a single line change. 
Adding @zaccharieramzi for review as this function was initially coded by him

Return Linear adjoint operator of coefficients

---

modopt/signal/wavelet.py

- set default `trim` option to `False`
- renamed `_trim_filter` to `trim_filter` for better API visibility
- updated docstrings
- resolves #91

get_mr_filters fix

---

modopt/signal/wavelet.py
requirements.txt

- set `dtype` to `float` for `call_mr_transform`
- removed cap on scipy version
- resolves issue #77

call_mr_transform dtype fix

---

modopt/opt/gradient.py

This PR aims to solve issue #100 .
The proposed changes in the issue were done.

Adding verbose attribute to GradParent to solve issue #100

---

README.md
docs/source/about.rst
docs/source/index.rst
docs/source/installation.rst

Final clean up of documentation before release

Release cleanup

---

README.md

Update README for tqdm dependency
