CEA-COSMIC/ModOpt

modopt/opt/algorithms.py
modopt/tests/test_opt.py

Restarting fista

---

modopt/opt/__init__.py
modopt/opt/proximity.py
modopt/tests/test_opt.py

This solves #36 .
RE the cost method: I don't really know why the general `*args` form was kept for the cost. I would guess that it's only ever the first argument (i.e. the data) that is used. As a matter of fact it's the only one used in the code as far as I see.

Linear comp prox

---

modopt/signal/wavelet.py

This PR solves #50 .
The trimming is done rather conservatively, keeping a square shape for the filter. This was done for now assuming a 2D filter.

added filter trimming in get_mr_filters

---

.travis.yml
CONTRIBUTING.md
README.rst
docs/source/index.rst
modopt/base/np_adjust.py
modopt/base/transform.py
modopt/info.py
modopt/interface/log.py
modopt/math/convolve.py
modopt/math/matrix.py
modopt/math/stats.py
modopt/opt/algorithms.py
modopt/opt/cost.py
modopt/opt/proximity.py
modopt/opt/reweight.py
modopt/plot/cost_plot.py
modopt/signal/filter.py
modopt/signal/svd.py
modopt/signal/validation.py
modopt/signal/wavelet.py
setup.py

- Removed all dependencies on `future`
- Removed imports from `builtins`
- Updated documentation
- Set minimum versions of package dependencies to latest, which only support Python v3.5+
- Added travis build for Python v3.7
- Updated package version to 1.4.0

Dropped support for Python < v3.5

---

setup.py

This PR fixes the dependency issues with PySAP, as earlier ModOpt forces one particular version of scipy, which causes a chain of issues that percolated to numpy, astropy etc.

Fix dependency of scipy, make it scipy>=1.3

---

README.rst
docs/source/index.rst
modopt/info.py
modopt/math/metrics.py
modopt/tests/test_math.py

- Updated SSIM with latest changes to Scikit-Image.
- Updated corresponding test.

fix for ssim

---

modopt/math/metrics.py
modopt/tests/test_math.py

This solves issue #72, it checks the python version and imports the right function

Fixing the incompatibilities with the different python version

---

modopt/opt/__init__.py
modopt/opt/proximity.py
modopt/tests/test_opt.py

This implements the squared k-support norm and solves #68 .
The implementation of the proximity operator is based on [this](http://jmlr.org/papers/volume17/15-151/15-151.pdf) paper although it has originally been proposed [here](https://papers.nips.cc/paper/4537-sparse-prediction-with-the-k-support-norm.pdf)

Implementation of the K-support norm proximity operator

---

modopt/opt/algorithms.py
modopt/opt/cost.py
modopt/tests/test_opt.py

This PR resolves #87 :
With this PR, the cost is **never** calculated by default, however, the user has an option to allow for the computation of cost at every Nth iteration as earlier.\
As this is a small PR, it also resolves #84

Ensure cost is never calculated in if `cost_interval=None` and call metrics at last iteration

---

.travis.yml
modopt/opt/algorithms.py
modopt/tests/test_opt.py

- Added `step_size` parameter to `SetUp` class.
- Made conditional assignment for step size parameters in each algorithm.
- Added unit test using `step_size` parameter.

Added generic step_size parameter to algorithm SetUp

---

.travis.yml
MANIFEST.in
README.rst
docs/source/conf.py
docs/source/index.rst
docs/source/modopt.base.rst
docs/source/modopt.interface.rst
docs/source/modopt.math.rst
docs/source/modopt.opt.rst
docs/source/modopt.plot.rst
docs/source/modopt.rst
docs/source/modopt.signal.rst
docs/source/modules.rst
docs/source/plugin_example.rst
docs/source/setup.rst
modopt/info.py
modopt/signal/wavelet.py

Added `MANIFEST.in` file and updated version for PyPi.

Added manifest

---

.travis.yml
README.rst
modopt/tests/test_opt.py
setup.cfg
setup.py

- Dropped Python 3.5 support
- Updated pycodestyle options for pytest
- Updated Ubuntu distribution for Travis
- Made minor fix to `test_d_support_norm` unit test

Updated pycodestyle testing and options

---

modopt/opt/algorithms.py

Currently, we converge and break only if verbosity is on. Switching it so that the functions that converge can be reported also!

Update flag for convergence

---

modopt/base/backend.py
modopt/math/matrix.py
modopt/opt/algorithms.py
setup.cfg

I have refactored the codes and made it more meaningful.
With this PR, we can support differentiable optimization on all the algorithms.
Finally, I incorporated #111 in here with right code styles

Add support for tensorflow backend which allows for differentiability

---

modopt/base/backend.py

It looks like we had an else if when we merged the tensorflow GPU codes.
This used to send numpy as the module in bad cases. This is a minor but good fix for the release.

MInor bug in `get_array_module`

---

.github/workflows/ci-build.yml
modopt/base/backend.py
modopt/tests/test_base.py
setup.cfg

These tests run only if tensorflow and cupy are installed.
@sfarrens can we add this to be tested with installs? 
I am not sure how long it will take to run.
ALso, these tests found a minute but a crucial bug which could be included in the release.

Add tests for modopt.base.backend and fix minute bug uncovered

---

MANIFEST.in
README.md
docs/source/dependencies.rst
docs/source/index.rst
setup.py

- Updated GPU dependency documentation to include TensorFlow
- Updated package version to v1.5.1

Release cleanup

---

.github/workflows/ci-build.yml
MANIFEST.in
README.md
docs/source/dependencies.rst
docs/source/index.rst
modopt/base/backend.py
modopt/math/matrix.py
modopt/opt/algorithms.py
modopt/tests/test_base.py
modopt/tests/test_opt.py
setup.cfg
setup.py

- Bug fix for metrics #110
- Bug fix for convergence #115 
- TensorFlow array support with unit tests
- Minor clean up
- #112
- #116
- #124
- #126
- #128

Version 1.5.1 patch release

---

.pyup.yml
develop.txt
docs/requirements.txt
docs/source/dependencies.rst
requirements.txt
setup.cfg

- closes #144
- closes #169
- closes ModOpt part of [this issue](https://github.com/CEA-COSMIC/pysap/issues/164)
- unpinned package and development requirements and set minimum versions
- updated `.pyup.yml` to prevent it from opening PRs to pin these dependencies
- updated pinned versions for API documentation build dependencies (these should not impact users)
- updated `description-file` -> `description_file` in `setup.cfg` (to remove deprecation warning)

Unpin package dependencies

---

modopt/opt/proximity.py
modopt/signal/svd.py
modopt/tests/test_opt.py
setup.cfg

This PR adds a  Singular Value Threshold Operator. This does exactly the same that `LowRankMatrix` but faster (roughly 10 times, it depends on the threshold value, notebook and data available upon request). 
Basically instead of computing all the singular value, and perform the thresholding, we only compute the one above the threshold, which save a lot of computation. 
I left the legacy version for now, but this should act as a drop in replacement.

Fast Singular Value Thresholding 

---

modopt/opt/gradient.py

- closes #204
- added `input_data_writeable` option to `GradParent`

added writeable input data array feature for benchopt

---

develop.txt
modopt/opt/linear.py
modopt/opt/proximity.py
setup.cfg

This PR fixes the few linting errors yielded by pydocstyle.

[lint] pydocstyle compliance.

---

modopt/math/matrix.py
modopt/tests/test_math.py

This PR fix #211 and implement the correct power method. 
Some other changes are also done to avoid to recompute norms.

Power method: fix #211

---

modopt/opt/algorithms/base.py
modopt/opt/algorithms/forward_backward.py
modopt/opt/algorithms/primal_dual.py
requirements.txt

This PR is my proposal to implement #216 
It works great with notebook and script, and make the output less clutter when running multiples optimizer sequentially. This allow for instance to have nested progress bar without flooding stdout.
It is obviously transparent to the end user, when no progressbar handle is manually provided.
An example of usage (taken from [pysap-fmri](https://github.com/paquiteau/pysap-fmri):
```python
progbar_main=trange(len(kspace_data))
progbar = tqdm(total=max_iter_per_frame)
for i in progbar_main:
grad_op = self.get_grad_op(
fourier_ops[i],
input_data_writeable=True,
**grad_kwargs)
grad_op._obs_data = kspace_data[i, ...]
opt = initialize_opt(opt_name=self.opt_name,
grad_op=grad_op,
linear_op=self.space_linear_op,
prox_op=self.space_prox_op,
x_init=next_init, …
```

Switch from progressbar to tqdm

---

docs/source/refs.bib
modopt/opt/algorithms/__init__.py
modopt/opt/algorithms/admm.py
modopt/opt/cost.py
modopt/tests/test_algorithms.py
setup.cfg

Hi, 
This is a WIP for adding (finally) the ADMM solver, and its variation Fast ADMM proposed by Goldstein et al. [^1]
I plan to add test in the future, but I think the test module for the algorithm requires a strong refactoring, I will probably do a separated PR for that also (see #262)
[^1] T. Goldstein, B. O’Donoghue, S. Setzer, and R. Baraniuk, “Fast Alternating Direction Optimization Methods,” SIAM J. Imaging Sci., vol. 7, no. 3, pp. 1588–1623, Jan. 2014, doi: [10/gdwr49](https://doi.org/10/gdwr49).

Add support for ADMM

---

modopt/opt/linear/__init__.py
modopt/opt/linear/base.py
modopt/opt/linear/wavelet.py
modopt/tests/test_opt.py

This PR add support for Wavelet Transform directly in Modopt, relying solely on PyWavelet, as an alternative to the redundant implementation of PySAP wavelet in the various plugins. 
Test and examples are coming in a near future.

Add Wavelet support

---

modopt/opt/linear/wavelet.py
modopt/opt/proximity.py
modopt/tests/test_opt.py

This PR add a new optional library for computing wavelet on GPU, using the pytorch wavelet toolbox. In order to make things easier, a wrapper using cupy is also provided. 
The current support for GPU array (e.g. using cupy instead of numpy) is not possible everywhere yet. I propose that we tackle each operators/group of operator separatly. A possible way of doing is shown for `SparseThreshold` but maybe a more generic way is possible (using a decorator maybe?).

Add GPU Wavelet transform support.
